const products=[
    {
        id:1,
        nombre:"Vans",
        precio: 2050,
        img:"../Imagenes/nike1.jpg",
        categoria:"Zapatilla",
    },
    {
        id:2,
        nombre:"Vans",
        precio:35200,
        img:"../Imagenes/vans2.jpg",
        categoria:"Buzo",
    },
    {
        id:3,
        nombre:"Nike",
        precio:2321,
        img:"../Imagenes/nike1.jpg",
        categoria:"gorra",
    },
    {
        id:4,
        nombre:"Nike",
        precio:5555,
        img:"../Imagenes/nike2.jpg",
        categoria:"Zapatilla",
    },
    {
        id:5,
        nombre:"Puma",
        precio:4322,
        img:"../Imagenes/puma1.jpg",
        categoria:"Remera",
    }
]